spring.application.name=booking-service

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/hotels
spring.datasource.username=root
spring.datasource.password=rhemita2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://192.168.42.126:8761/eureka
eureka.instance.prefer-ip-address=true